name: Build and Deploy CI/CD

on: ["push", "pull_request"]


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: pull git repo
        uses: actions/checkout@v2
      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip